import "./tests/let-i8.test"
import "./tests/all-types.test"
import "./tests/platform-matrix.test"
import "./tests/platform-targets.test"
import "./tests/binary-inference.test"
import "./tests/platform-specific.test"
import "./tests/strict-mode.test"
import "./tests/literal-inference.test"
import "./tests/literal-overflow.test"
import "./tests/compiler-backend.test"
import "./tests/file-param.test"
import "./tests/expect-matchers.test"
import "./tests/hooks.test"
import "./tests/async.test"
import { printSummary } from "./engine"

printSummary()