import "./let-i8.test"
import "./all-types.test"
import "./platform-matrix.test"
import "./platform-targets.test"
import "./binary-inference.test"
import "./platform-specific.test"
import "./strict-mode.test"
import "./literal-inference.test"
import "./literal-overflow.test"
import "./compiler-backend.test"
import "./file-param.test"
import "./expect-matchers.test"
import "./hooks.test"
import "./async.test"
import "./jest-api.test"
import "./integer-overflow.test"
import "./integer-errors.test"
import "./integer-properties.test"
import "./safe-math-errors.test"
import "./diagnostics-registry.test"
import "./capability-matrix.test"
import { printSummary } from "../engine"

printSummary()