/* std/embedded.h — TSClang embedded runtime: hashmap, tasks, hash utils */
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

/* DJB2 hash for String keys */
static inline uint32_t tsc_djb2(String s) {
    uint32_t h = 5381;
    for (size_t i = 0; i < s.length; i++)
        h = ((h << 5) + h) + (uint8_t)s.data[i];
    return h;
}

/* ---- Open-addressing HashMap (String → i32) macros ---- *
 * The HashMap_string_i32 struct is generated by codegen.
 * All operations work on any struct with:
 *   String keys[N]; int32_t values[N]; bool used[N];
 *   size_t capacity; size_t count;
 */

/* Linear probe: find slot for key. Returns index, or capacity if map full. */
#define _TSC_HM_FIND(m, k) ({ \
    uint32_t _hf = tsc_djb2(k) % (m)->capacity; \
    size_t _tries = 0; \
    while (_tries < (m)->capacity && (m)->used[_hf] && !tsc_string_eq((m)->keys[_hf], (k))) { \
        _hf = (_hf + 1) % (m)->capacity; _tries++; \
    } \
    (int32_t)(_tries < (m)->capacity ? (int32_t)_hf : -1); \
})

#define tsc_hashmap_set_string_i32(m, k, v) do { \
    int32_t _si = _TSC_HM_FIND(m, k); \
    if (_si >= 0) { \
        if (!(m)->used[_si]) { (m)->used[_si] = true; (m)->keys[_si] = (k); (m)->count++; } \
        (m)->values[_si] = (v); \
    } \
} while(0)

#define tsc_hashmap_get_string_i32(m, k) ({ \
    int32_t _gi = _TSC_HM_FIND(m, k); \
    bool _gfound = _gi >= 0 && (m)->used[_gi] && tsc_string_eq((m)->keys[_gi], (k)); \
    (opt_i32){ .has_value = _gfound, .value = _gfound ? (m)->values[_gi] : 0 }; \
})

#define tsc_hashmap_has_string_i32(m, k) ({ \
    int32_t _hi = _TSC_HM_FIND(m, k); \
    (_hi >= 0 && (m)->used[_hi] && tsc_string_eq((m)->keys[_hi], (k))); \
})

#define tsc_hashmap_delete_string_i32(m, k) do { \
    int32_t _di = _TSC_HM_FIND(m, k); \
    if (_di >= 0 && (m)->used[_di] && tsc_string_eq((m)->keys[_di], (k))) { \
        (m)->used[_di] = false; (m)->count--; \
    } \
} while(0)

/* ---- Tasks scheduler (cooperative, polling-based) ---- */

#define tsc_tasks_add(_tsc_tasks, _tsc_name, _tsc_fn, _tsc_state) do { \
    size_t _ti = (_tsc_tasks)->_count; \
    if (_ti < sizeof((_tsc_tasks)->_slots) / sizeof((_tsc_tasks)->_slots[0])) { \
        (_tsc_tasks)->_slots[_ti].fn = (_tsc_fn); \
        (_tsc_tasks)->_slots[_ti].state = (_tsc_state); \
        (_tsc_tasks)->_slots[_ti].active = true; \
        (_tsc_tasks)->_slots[_ti].name = (_tsc_name); \
        (_tsc_tasks)->_count++; \
    } \
} while(0)

#define tsc_tasks_run(_tsc_tasks) do { \
    bool _any = true; \
    while (_any) { \
        _any = false; \
        for (size_t _ti = 0; _ti < (_tsc_tasks)->_count; _ti++) { \
            if ((_tsc_tasks)->_slots[_ti].active) { \
                (_tsc_tasks)->_slots[_ti].fn((_tsc_tasks)->_slots[_ti].state); \
                _any = true; \
            } \
        } \
    } \
} while(0)

#define tsc_tasks_stop(_tsc_tasks, _tsc_name) do { \
    for (size_t _ti = 0; _ti < (_tsc_tasks)->_count; _ti++) { \
        if ((_tsc_tasks)->_slots[_ti].active && tsc_string_eq((_tsc_tasks)->_slots[_ti].name, (_tsc_name))) { \
            (_tsc_tasks)->_slots[_ti].active = false; \
        } \
    } \
} while(0)
