import "./arrow-functions.test"
import "./asi.test"
import "./braces.test"
import "./comments.test"
import "./empty-lines.test"
import "./generics.test"
import "./indentation.test"
import "./line-breaks.test"
import "./line-length.test"
import "./method-chains.test"
import "./opening-brace.test"
import "./operator-spaces.test"
import "./quotes.test"
import "./semicolon.test"
import "./ternary.test"
import "./trailing-comma.test"
import "./type-annotation-spaces.test"
import "./union-types.test"
import { printSummary } from "../../../../../test-engine/src/engine.ts"

printSummary()
